### ISSUE TITLE
NLog.LogManager.Configuration reload causes RichTextBoxTarget to create a new form

### ISSUE THREAD

**Issue by dwanboweb** [NLog/NLog.Windows.Forms#154] opened 2023-10-12 02:10 UTC
Hi! Thanks for reporting this bug! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**NLog version**: (5.4)

**Platform**: ..Net 4.5 

```
LoggingConfiguration config = new LoggingConfiguration();

config.AddRule(LogLevel.Info, LogLevel.Fatal, new RichTextBoxTarget
{
    TargetRichTextBox = richTextBox1,
    MaxLines = 50,

}, "*");


NLog.LogManager.Configuration = config;
var logger1 = NLog.LogManager.GetCurrentClassLogger();
logger1.Info("test1");
//this make 'test2' been put out in a new form
NLog.LogManager.Configuration = NLog.LogManager.Configuration;
logger1.Info("test2");

```
--‘test2’ been out put in a new form instead of  richTextBox1 while using 'NLog.LogManager.Configuration = NLog.LogManager.Configuration'
![image](https://github.com/NLog/NLog/assets/17172451/06ff09dc-8ce8-482e-9e81-3ecfc44d041e)

**Comment by snakefoot** [comment] 2023-10-12 05:56
Thank you for the feedback. If you can figure out where it issue is in the RichTextBoxTarget-source-code:

- [RichTextBoxTarget.cs](https://github.com/NLog/NLog.Windows.Forms/blob/master/NLog.Windows.Forms/RichTextBoxTarget.cs)

Then we can look at improving the source-code.

**Comment by snakefoot** [comment] 2023-10-12 16:00
You are also wellcome to enable the [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging) and then post the output, and highlight where the unexpected behavior occurs.

This might help guesing where in the source-code the issue is.

**Comment by dwanboweb** [comment] 2023-10-13 02:17
The problem seems to be in RichTextBoxTarget.DetachFromControl, which will set TargetRichTextBox to null. When setting NLog.LogManager.Configuration to a new value, the setter will call config.close, which will invoke Target.Close() and then RichTextBoxTarget.DetachFromControl(). This will make TargetRichTextBox of RichTextBoxTarget null, and it will also affect the new value of Configuration when the new value is itself.
`
var config = NLog.LogManager.Configuration; // do some thing to config NLog.LogManager.Configuration = config; // in the setter of Configuration, TargetRichTextBox of RichTextBoxTarget will be null, and the new value is itself, so it will also affect the new value of Configuration`

**Comment by snakefoot** [comment] 2023-10-13 16:52
Notice that you are allowed to add new LoggingRules to the active `LogManager.Configuration`, without doing reassign `NLog.LogManager.Configuration = NLog.LogManager.Configuration;`

The trick is calling `NLog.LogManager.ReconfigExistingLoggers()` to commit/activate the changes to the active `LogManager.Configuration`

**Comment by snakefoot** [comment] 2023-10-29 14:59
Closing issue as resolved, due to inactivity

**Closed by snakefoot** 2023-10-29 14:59 UTC
Labels: question
